name: metallum
description: An API for Encyclopaedia Metallum (A.K.A Metal Archives).
version: 0.0.1
homepage: https://github.com/muniz95/metallum-api
author: Rodrigo Muniz <rodrigo.temiski1995@gmail.com>

environment:
  sdk: '>=1.20.1'

dependencies:
  html: any
  http: any

dev_dependencies:
  test: ^0.12.0
